import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#536372',
        'surface-tint': '#5f5e5e',
        'inverse-on-surface': '#9c9d9d',
        'secondary-container': '#cee5ff',
        'tertiary-container': '#dcedff',
        'on-secondary': '#f6f9ff',
        'on-primary-container': '#525151',
        'primary-fixed': '#e5e2e1',
        'on-primary': '#faf7f6',
        'on-tertiary-container': '#495867',
        'on-background': '#2d3435',
        'on-tertiary': '#f6f9ff',
        secondary: '#216394',
        background: '#f9f9f9',
        'on-surface': '#2d3435',
        outline: '#757c7d',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e4e9ea',
        'tertiary-fixed-dim': '#cedff1',
        'surface-variant': '#dde4e5',
        'on-error-container': '#752121',
        error: '#9f403d',
        'error-container': '#fe8983',
        'tertiary-fixed': '#dcedff',
        'on-surface-variant': '#5a6061',
        'secondary-dim': '#0a5787',
        'on-primary-fixed-variant': '#5c5b5b',
        'on-tertiary-fixed': '#374655',
        'primary-dim': '#535252',
        tertiary: '#516170',
        'surface-container': '#ebeeef',
        'tertiary-dim': '#455564',
        'surface-container-low': '#f2f4f4',
        'on-primary-fixed': '#403f3f',
        'on-error': '#fff7f6',
        'surface-dim': '#d4dbdd',
        'surface-bright': '#f9f9f9',
        'secondary-fixed-dim': '#b2d8ff',
        primary: '#5f5e5e',
        'inverse-primary': '#ffffff',
        'surface-container-highest': '#dde4e5',
        'secondary-fixed': '#cee5ff',
        'on-secondary-fixed-variant': '#1b6090',
        surface: '#f9f9f9',
        'inverse-surface': '#0c0f0f',
        'on-secondary-fixed': '#00436a',
        'on-secondary-container': '#065685',
        'error-dim': '#4e0309',
        'primary-fixed-dim': '#d7d4d3',
        'outline-variant': '#adb3b4',
        'primary-container': '#e5e2e1',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [forms, containerQueries],
};
